plugins {
    id 'net.neoforged.gradle.userdev' version '7.0.145'
}

version = '2.0.0'
group = 'com.rawr.automation'

base {
    archivesName = 'RawrAutomation'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    client {
        modSource project.sourceSets.main
    }
}

dependencies {
    implementation 'net.neoforged:neoforge:21.1.77'
}
